version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo-catapi
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cat-api:
    build: .
    container_name: cat-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env.docker

volumes:
  mongo_data:
